### PR TITLE
Add two default labels: 'framework' and 'language' to raw test results in allure

### PR DESCRIPTION
**Pull request by lpelypenko**
Hi to library contributors and maintenance,
Thank you very much for writing really nicely organized and tested typescript library and thank you for detailed `CONTRIBUTING.md` file.

**Objectives for this change**
Our team uses variety of different frameworks and they all use allure reporting. We want to index which test results are coming from which framework and all extensions that we use with allure (junit4, junit5, cypress, pytest) are adding 'framework' and 'language' into `the labels` array. Without it in TestCafe, our TestCafe tests are not indexed.

Example of how allure report looks like in junit5 allure extension:
```
{
  "attachments": [],
  "description": "",
  "fullName": "com.indeed.test.FooJUnit5Test.testPassedRetriedThreeTimes",
  "historyId": "1412e1206ef3da2fe04e10a6624ebaa8",
  "labels": [
    {
      "name": "host",
      "value": "XXXX"
    },
    {
      "name": "thread",
      "value": "59625@XXXXX.Test worker(12)"
    },
    {
      "name": "framework",
      "value": "junit-platform"
    },
    {
      "name": "language",
      "value": "java"
    },
    {
      "name": "package",
      "value": "com.indeed.test.FooJUnit5Test"
    },
    {
      "name": "testClass",
      "value": "com.indeed.test.FooJUnit5Test"
    },
    {
      "name": "testMethod",
      "value": "testPassedRetriedThreeTimes"
    },
    {
      "name": "suite",
      "value": "com.indeed.test.FooJUnit5Test"
    }
  ],
  "links": [],
  "name": "testPassedRetriedThreeTimes() (Repetition 3 of 3)",
  "parameters": [],
  "stage": "finished",
  "start": 1610591701664,
  "status": "skipped",
  "statusDetails": {
    "flaky": false,
    "known": false,
    "message": "Turn off the remaining repetitions as the test ultimately passed",
    "muted": false
  },
  "steps": [],
  "stop": 1610591701664,
  "uuid": "068b156d-df1b-460d-914e-85b2e2fc53da"
}
```

Example of current `testcafe-reporter-allure` report: 

```
{
    "uuid": "bf1d235f-a415-46f6-9f47-e5c4a45e6e34",
    "historyId": "f68ffef2-b7cc-442a-af80-0e2b4df2fffc",
    "status": "passed",
    "statusDetails": { "message": "", "trace": "" },
    "stage": "finished",
    "steps": [],
    "attachments": [],
    "parameters": [
        { "name": "accessibility", "value": "true" },
        { "name": "functional", "value": "false" },
    ],
    "labels": [
        { "name": "severity", "value": "Normal" },
        { "name": "suite", "value": "suite name" }
    ],
    "links": [],
    "start": 1625561608968,
    "name": "test",
    "fullName": "test",
    "stop": 1625561664345
}
```

I have reviewed `pytest` allure extension and it also produces `labels` with `framework` and `language`: 
```
"labels": [
    {
      "name": "parentSuite",
      "value": "tests"
    },
    {
      "name": "suite",
      "value": "test_example"
    },
    {
      "name": "subSuite",
      "value": "TestCase"
    },
    {
      "name": "host",
      "value": "IT-USA-VX0119"
    },
    {
      "name": "thread",
      "value": "17359-MainThread"
    },
    {
      "name": "framework",
      "value": "pytest"
    },
    {
      "name": "language",
      "value": "cpython3"
    },
    {
      "name": "package",
      "value": "tests.test_example"
    }
  ],
```

**Summary of changes**

-  Added two labels: `framework` and `languages` that will be always added to every test result
- Updated tests
- Updated `CONTRIBUTING.md` file

### CODE REVIEW

**Comment by vanhoofmaarten** [comment]
Hi @lpelypenko. 

Thank you for this contribution. 

At first glance, this looks like a very thorough and well implemented feature! I will dedicate some time this week to review this PR.

**Comment by lpelypenko** [comment]
Thank you @vanhoofmaarten!

**Comment by Ronaldvdh-ISAAC** [comment]
Hi @lpelypenko,
We discussed your change and we were wondering what the aim was for adding labels exactly.
With your explanation it seems you have some extra software running to index allure-results before the allure-report is generated? We ran your PR and we couldn't find the added labels in the report. According to the allure documentation you have https://docs.qameta.io/allure/#_usage_4 only a few possible labels which influence the report.

We do have a way to add custom metadata to tests https://www.npmjs.com/package/@isaac.frontend/testcafe-reporter-allure/v/0.1.0#metadata. These will be converted to parameters in the allure report so can see and search on them within the report.

Would that also solve your problem?

**Comment by lpelypenko** [comment]
Hi @Ronaldvdh-ISAAC, 
our internal script is scanning all allure result files and index them. I can see in raw results of your e2e tests that implemented fields are populated with my change in allure-results files and we actually not aiming to see them in final report. We are using allure result files as a common point to analyze all of our test coverage from all frameworks across different departments and it works great except for TestCafe. They all have the same structure and it is easy to parse them.
 
'framework' and 'language' fields exist in all investigated by me allure extensions for other frameworks like allure-pytest, allure junit5 and I consider this fields as standard fields that belongs to default labels and they should not be passed as part of test metadata.

If we use custom meta tags you suggested, it will add desired labels in allure-results but it would mean that we would need to make changes in meta tags for massive amount of tests and also across different teams/departments. I have a doubt that  it will be adopted this way so this solution will not be useful. Having them as default values will be adopted by only bumping the library without code change.

My change will not affect negatively any existing usage but it will give us more seamless way to add indexing of language and framework for TestCafe.

**Comment by dshuga** [comment]
> 'framework' and 'language' fields exist in all investigated by me allure extensions for other frameworks like allure-pytest, allure junit5 and I consider this fields as standard fields that belongs to default labels and they should not be passed as part of test metadata.

+1

**Comment by Ronaldvdh-ISAAC** [comment]
Thank you for your answer, makes it more clear that you really only use the allure-results for your use-case and not the report (we were focusing on the report).

The labels `language` and `framework` are indeed in the list of possible labels documented (poorly) by allure. And i was surprised to find out we didn't implement them in the first place :).

I am going to discuss with @vanhoofmaarten

**Comment by vanhoofmaarten** [comment]
Hey @lpelypenko,

If I'm correct, I believe you've reverted one commit to many. (See: https://github.com/isaaceindhoven/testcafe-reporter-allure/pull/90/commits/06aa5b4811cc4ccd4f10ac38546d8e6fe994abb8)

Could you revert that revert? Then we can continue with merging this PR.

**Comment by vanhoofmaarten** [comment]
Hmmm, merging #91 also closes this one. That's unfortunate. @lpelypenko  Would you be willing to open a new PR?

**Comment by lpelypenko** [comment]
@vanhoofmaarten I am so sorry! It was my mistake with handling `develop` branch in my fork. I wanted to do a separate bug fix and wanted to start it from original develop without this change.

I have created new pull request https://github.com/isaaceindhoven/testcafe-reporter-allure/pull/92

**Pull request merged**
